# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acordao',
            fields=[
                ('acordao_id', models.AutoField(primary_key=True, serialize=False)),
                ('processo', models.CharField(blank=True, max_length=100, null=True)),
                ('seccao', models.CharField(blank=True, max_length=100, null=True)),
                ('num_convencional', models.CharField(blank=True, max_length=100, null=True)),
                ('relator', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('votacao', models.CharField(blank=True, max_length=50, null=True)),
                ('aditamento', models.TextField(blank=True, null=True)),
                ('trib_recorrido', models.TextField(blank=True, null=True)),
                ('proc_trib_recorrido', models.CharField(blank=True, max_length=100, null=True)),
                ('data_dec_recorrida', models.DateField(blank=True, null=True)),
                ('txt_integral_flag', models.CharField(blank=True, max_length=5, null=True)),
                ('txt_parcial_flag', models.CharField(blank=True, max_length=5, null=True)),
                ('privacidade', models.IntegerField(blank=True, null=True)),
                ('meio_processual', models.TextField(blank=True, null=True)),
                ('recorrente', models.TextField(blank=True, null=True)),
                ('decisao', models.TextField(blank=True, null=True)),
                ('indic_eventuais', models.TextField(blank=True, null=True)),
                ('area_tematica', models.TextField(blank=True, null=True)),
                ('doutrina', models.TextField(blank=True, null=True)),
                ('legis_nacional', models.TextField(blank=True, null=True)),
                ('juris_nacional', models.TextField(blank=True, null=True)),
                ('sumario', models.TextField(blank=True, max_length=-1, null=True)),
                ('txt_parcial', models.TextField(blank=True, null=True)),
                ('txt_integral', models.TextField(blank=True, null=True)),
                ('html_txt_integral', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('date_loaded', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acordao',
            },
        ),
        migrations.CreateModel(
            name='AcordaoDescritor',
            fields=[
                ('acordao_desc_id', models.AutoField(primary_key=True, serialize=False)),
                ('descritor', models.TextField(blank=True, null=True)),
                ('acordao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jurisapp.Acordao')),
            ],
            options={
                'db_table': 'acordao_descritor',
            },
        ),
        migrations.CreateModel(
            name='AcordaoRecorrido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorrido', models.TextField(blank=True, null=True)),
                ('acordao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jurisapp.Acordao')),
            ],
            options={
                'db_table': 'acordao_recorrido',
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id_name', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('long_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tribunal',
            },
        ),
        migrations.AddField(
            model_name='acordao',
            name='tribunal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jurisapp.Tribunal'),
        ),
    ]
