# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acordaorecorrido',
            name='id',
        ),
        migrations.AddField(
            model_name='acordaorecorrido',
            name='acordao_recorrido_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
