# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordao',
            name='num_convencional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acordao',
            name='numero',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acordao',
            name='proc_trib_recorrido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acordao',
            name='processo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acordao',
            name='relator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acordao',
            name='seccao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acordao',
            name='votacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
