# Generated by Django 2.2.10 on 2020-03-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email_address'),
        ),
    ]
