# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 07:55
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurisapp', '0002_auto_20171029_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordao',
            name='searchable_idx_col',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
