# Generated by Django 2.2.10 on 2020-03-14 20:44

from django.db import migrations
import jurisapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisapp', '0003_auto_20200314_2025'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', jurisapp.models.UserManager()),
            ],
        ),
    ]
