# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisapp', '0003_acordao_searchable_idx_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordao',
            name='html_txt_parcial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
