# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisapp', '0004_acordao_html_txt_parcial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordao',
            name='date_loaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
