# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisapp', '0005_auto_20180218_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordao',
            name='descritores',
            field=models.TextField(blank=True, null=True),
        ),
    ]
