# Generated by Django 2.2.10 on 2020-03-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurisapp', '0006_customer_customeruser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customeruser',
            table='customer_user',
        ),
    ]
