# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurisapp', '0007_remove_acordao_searchable_idx_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acordaodescritor',
            name='acordao',
        ),
        migrations.DeleteModel(
            name='AcordaoDescritor',
        ),
    ]
