# Generated by Django 2.2.10 on 2020-03-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurisapp', '0007_auto_20200324_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customeruser',
            old_name='user_id',
            new_name='user',
        ),
    ]
